# Generated by Django 4.1.4 on 2022-12-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitorig',
            new_name='Monitoring',
        ),
    ]
